version: "3"

services:
  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: cristmas_shop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5555:5555